In [4]:
import pandas as pd
import csv
import numpy as np

In [5]:

#n = no of industries in the model
n = 3
leontief_matrix = np.zeros((3,3))
with open('leontief_model.txt') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    i = 0
    for row in csv_reader:
        if(i!=0):
            for j in range(n):
                leontief_matrix[i-1][j] = row[j]
        i+=1
print(leontief_matrix)
I = np.identity(n)
#open system
demand = [150,200,200]
l_solve = I - leontief_matrix
production_vector = np.linalg.solve(l_solve,demand)
print(production_vector)

#closed system (Note the matrix is an open system matrix, so the values will be weird when I use it as a closed system)
eigvals, eigvecs = np.linalg.eig(leontief_matrix)
print(eigvals)
for i in range (3):
    print(eigvecs[i][0])

[[0.3 0.2 0.1]
 [0.2 0.1 0.3]
 [0.1 0.2 0.3]]
[419.03409091 475.85227273 481.53409091]
[ 0.6  0.2 -0.1]
-0.577350269189626
-0.5773502691896257
-0.5773502691896256
